name: Extractor Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: "30 17 * * *"

jobs:
  run_extractor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Install requests module
        run: pip install yfinance==0.2.18 pandas==2.0.1 openpyxl==3.1.2 requests==2.29.0

      - name: Aktuelles Datum abrufen
        id: date
        run: |
          echo "date=$(date -d '1 day ago' +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Run Extractor
        timeout-minutes: 10
        run: python -c "import os; from collector.exctract_data.cryptocurrencies.exctract_crypto_data import _run_crypto_extractor; from collector.exctract_data.stocks.exctract_stock_data import _run_stock_extractor; date = os.getenv('date'); _run_crypto_extractor(date); _run_stock_extractor(date)"

      - name: Set up Git
        run: |
          git config --global user.name "Max Ruffo"
          git config --global user.email "max.ruffo@student.htw-berlin.de"
          
      - name: Commit and Push
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
          DATE: ${{ env.date }}
        run: |
          git pull
          git add .
          git commit -m "Daten aktualisiert am $DATE" --allow-empty
          git push
